### ISSUE TITLE
Can we do a minor/patch release of nbformat? 

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbformat#104]
The new API needs to be made available on pypi for me to be able to use it in nbconvert… this doesn't seem like a major change, and I'd like to make the release in the next few days if at all possible.

**Comment by mpacer** [comment]
I guess more generally, how do we decide when nbformat is released? It seems like it should be more tightly controlled and coördinated than many other packages.

**Comment by mpacer** [comment]
@minrk @takluyver What do we need to do in order to release a minor version of nbformat? There are no guidelines for nbformat releases.

**Comment by takluyver** [comment]
I think it needs a bit more coordination when we're changing the version number of the notebook format itself, but other than that the nbformat package is just a standard package which we can release like any other.

I don't see any reason not to do a new minor release now if you're happy with the package as is. The current release is 4.3, so a new release would be 4.4. You can see [the changes since 4.3](https://github.com/jupyter/nbformat/compare/4.3.0...master).

- [ ] Update changelog
- [ ] Set version number to 4.4 with no 'dev' suffix.
- [ ] Ensure all tests are passing on CI & locally
- [ ] Upload to PyPI
- [ ] Make a git tag
- [ ] Set version number to 4.5.dev

**Comment by mpacer** [comment]
Also (thanks to a note in the `_version.py` we need to add one more task, updating the package.json version number.

**Comment by mpacer** [comment]
I'm guessing you actually meant 4.4.0 (since we use semver) and then 4.5.0.dev? And that that only applies to the `_version.py`

Should the git tag match the actual semver version number or should it match the abbreviated version?

Should the `package.json` actually be set to be 4.5.0? I.e., not 4.5.dev? That fits with the previous patterns.

**Comment by mpacer** [comment]
Writing a new version instead of editing your list now since it's sufficiently different:

- [x] Update changelog
- [ ] Set version number to 4.4.0 (with no 'dev' suffix).
    - [ ] [`nbformat/_version.py`][pyversion]
    - [ ] [`package.json`][jsonversion]
- [ ] Ensure all tests are passing on CI & locally
- [ ] Upload to PyPI
- [ ] Make a git tag
- [ ] Set the [`nbformat/_version.py`][py_version] version number to 4.5.0.dev
- [ ] Set the [`package.json`][jsonversion] version number to 4.5.0

[pyversion]: https://github.com/jupyter/nbformat/blob/master/nbformat/_version.py
[jsonversion]: https://github.com/jupyter/nbformat/blob/master/package.json

**Comment by minrk** [comment]
> Should the package.json actually be set to be 4.5.0? I.e., not 4.5.dev? That fits with the previous patterns.

Yes, I think so

**Comment by takluyver** [comment]
Is the plan to squeeze #107 in before a release? Or do you want to release before merging that?

**Comment by minrk** [comment]
I'm okay either way. #107 seems nice to me, but if @mpacer would rather have a release before finishing that, that works for me.

**Comment by mpacer** [comment]
I'm ok holding off until #107 is ready. I will make some changes to the v4 nbbase code removing redundant `from_dict` calls since the `update` change is now included. Then it should be ready and I can release this then the nbconvert preprocessor checks and the tag preprocessor and then hopefully we can release that.

**Comment by mpacer** [comment]
Alright… well, I merged #108 and tagged 9c7c07233 with `4.4.0` and tried to `twine upload` … but then I discovered that I don't have rights on pypi to push an update to nbformat.

If someone wants to give me those rights I'm nearly done with the release.

**Comment by mpacer** [comment]
For anyone wanting to help with this by authorising me: my pypi username is mdpacer.

**Comment by minrk** [comment]
@mpacer I've added you on nbformat

**Comment by mpacer** [comment]
Thanks @minrk! I made the release and am just waiting on the conda-forge build here. 

I should probably add official docs about how to manage a release so that we don't have to make it up everytime we go along.

**Comment by takluyver** [comment]
We actually have a central document on making a release, but I didn't know about it until I went looking:
http://jupyter.readthedocs.io/en/latest/developer-docs/releasing.html

Most of the steps are the same for releasing any Jupyter/IPython Python package. The only special thing for nbformat is that there's one extra file containing a version number. I'd like to avoid duplicating this information on every package we have, because once you've got that many copies of the docs, it's really easy for them to get out of date.

**Comment by minrk** [comment]
I've used [bumpversion](https://github.com/peritus/bumpversion) in a few projects where I had an extra place or two to keep in sync. It usually works well enough.

**Comment by takluyver** [comment]
Neat. I had a go at making something like that, but it wasn't as configurable, so it would have had issues with our `version_info = (4, 5, 0, 'dev')` definitions.

**Comment by takluyver** [comment]
#109 adds config for bumpversion.
