### ISSUE TITLE
ValidationError and NotebookValidationError cannot be raised directly

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbformat#105]
For some reason ValidationError and NotebookValidationError on py3.6 are not able to be used in the context of https://github.com/jupyter/nbconvert/pull/645, in which we are trying to validate notebooks in nbconvert in-between each preprocessor step. 

@takluyver asked for us to catch and provide the name of the preprocessor and I tried this a few ways, but the crucial one that should have worked (in my opinion) is:

```python
        for preprocessor in self._preprocessors:
            nbc, resc = preprocessor(nbc, resc)
            try: 
                nbformat.validate(nbc)
            except nbformat.ValidationError:
                raise "Error found in {}".format(preprocessor.__class__.__name__)
```
which raised
```
E               TypeError: exceptions must derive from BaseException
```

or a few variations on swapping out the end of that:

```python
            except nbformat.validator.NotebookValidationError as e:
                raise e("Error found in {}".format(preprocessor.__class__.__name__))
```

```python
            except nbformat.ValidationError as e:
                raise e("Error found in {}".format(preprocessor.__class__.__name__))
```

both raising:
``` 
E               TypeError: 'NotebookValidationError' object is not callable
```

But that fails in the wrong way…

The closest I could get to it working was:

```python
            except nbformat.ValidationError:
                raise nbformat.validator.better_validation_error("Error found in {}".format(preprocessor.__class__.__name__), 4, 0)
```

But even that had some unexpected behaviour: 
```
error = 'Error found in PizzaPreprocessor', version = 4, version_minor = 0

    def better_validation_error(error, version, version_minor):
        """Get better ValidationError on oneOf failures

        oneOf errors aren't informative.
        if it's a cell type or output_type error,
        try validating directly based on the type for a better error message
        """
>       key = error.schema_path[-1]
E       AttributeError: 'str' object has no attribute 'schema_path'
```

Can someone explain why this is designed the way it is (on the one hand) and how we're supposed to use these Exception objects (on the other hand?)? 

Or, are these Exceptions not written appropriately (as suggested by the not inheriting from `BaseException` and not callable bits)? 

I can see in the definition of [jsonschema._Error]( https://github.com/Julian/jsonschema/blob/master/jsonschema/exceptions.py#L16) which is the ancestor of `ValidationError` (and therefore `NotebookValidationError`) that these **do** eventually inherit from `BaseException` via `Exception`.  
But I'm genuinely confused as to how code like this: [`return NotebookValidationError(error, ref)`](https://github.com/jupyter/nbformat/blob/988571d1815e9d25440038d6b620c17ba7040bd7/nbformat/validator.py#L234 ) *ever* works appropriately.

cc: @minrk @Carreau

**Comment by takluyver** [comment]
The first error ("exceptions must derive from BaseException") means you can't raise a string as an error. It used to be allowed, so some outdated info online might tell you to do that, but it's no longer possible; the argument to `raise` has to be an exception object or class.

The second error ("'NotebookValidationError' object is not callable") is because `e` is an *instance* of the exception type. `NotebookValidationError` is a class, so calling it with a message creates an instance. You can't then call the instance itself. `type(e)` would give you `NotebookValidationError`.

Adding info to an exception is, unfortunately, a bit messy. It's easier to catch one exception and raise a new one to replace it, but that's not what we want to do here. Exception chaining in Python 3 helps with this - you can raise a new error and the traceback still shows the old one. But as we're still supporting Python 2 for now, I would probably do this:

```python
try: 
    nbformat.validate(nbc)
except nbformat.ValidationError:
    self.log.error('Notebook is invalid after preprocessor %r', preprocessor)
    raise  # With no args, raise re-raises the same exception
```

The information about which preprocessor is involved goes through the logging system instead of the exception system, but that should be good enough for someone to work out which preprocessor went wrong.
