### ISSUE TITLE
Validation of an invalid notebook succeeds

### ISSUE THREAD

**Issue by scjody** [jupyter/nbformat#123]
Validation of an invalid notebook succeeds starting with `4.3.0`.

### Test case

```python
import nbformat
nbformat.validate({'foo': 'bar', 'A': 'B', 10: 12}) # Should raise an exception
```

### Expected result

* Raises an exception

### Actual result
* returns `None`
* Prints `No schema for validating v1 notebooks`

I don't see anything relevant in your changelog, so this looks like an unintended change.

### Version history
* `4.3.0`, `4.4.0`, `master`: returns `None`
* `4.0.0`, `4.1.0`, `4.2.0`: raises `AttributeError`

### System information

```python
$  python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'b467d487e',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '5.5.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-109-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Nov 23 2017, 15:49:48) \n[GCC 4.8.4]'}
```

**Comment by takluyver** [comment]
Yeah, that definitely should raise an exception. It's treating it as format version 1 (because we introduced the version numbers with format version 2), and it doesn't know how to check version 1, so it assumes it's fine. #85 looks like the change that affected it.

The proper thing to do would be to add a schema for v1, but that's so old that it's probably OK to assume it's invalid.

@vidartf it was your PR that changed it so an empty dictionary would validate. Is it going to cause you problems if it fails to validate?

**Comment by vidartf** [comment]
@takluyver I think the main point of that PR was that it should raise a `ValidationError` instead of an `AttributeError`.

**Comment by takluyver** [comment]
Aha, thanks. Possibly some other change coincidentally cancelled the validation error. So it should be fine to throw ValidationError when the version isn't recognised.

**Comment by vidartf** [comment]
> So it should be fine to throw ValidationError when the version isn't recognised.

👍

**Comment by takluyver** [comment]
@scjody do you want to make a PR?

**Comment by scjody** [comment]
@takluyver Sure, it sounds straightforward given the details you folks provided.

I'm in the middle of a high priority project and I've successfully worked around this issue, so it may take me a couple of weeks to get to it - I hope that's OK 😸
