### ISSUE TITLE
Security Issue: Vulnerable XML parser

### ISSUE THREAD

**Issue by An7i21** [jupyter/nbformat#132]
**Using xml.etree.ElementTree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.fromstring with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called**

[Source](https://github.com/jupyter/nbformat/blob/9dd1b8719c9095eaebce1846416bb3a5e939758f/nbformat/v2/nbxml.py#L112)

[Same issue reference at "Jupiter.nbconvert"](https://github.com/jupyter/nbconvert/issues/706)

I believe it worth checking this issue globally at Jupiter.

**Comment by takluyver** [comment]
Ugh, I'd forgotten we once had an XML-based notebook format. This was removed in newer versions of the file format, and I've never heard from anyone using it. But the design of the library allows it to still open any file format that was ever supported.

I'm inclined to remove the XML parsing code entirely, and see if anyone complains about it. Maybe trying to use it can raise an error with a message like: "Loading notebooks from XML was removed because of security issues. We are not aware of anyone using it, so please get in touch if you are."

**Comment by westurner** [comment]
https://pypi.org/project/defusedxml/ also lists a number of attack vectors
and other things to consider.

- https://pypi.org/project/defusedxml/#attack-vectors
- https://pypi.org/project/defusedxml/#other-things-to-consider
- https://pypi.org/project/defusedxml/#how-to-avoid-xml-vulnerabilities

**Comment by takluyver** [comment]
Looking more at this, I don't think it actually creates security vulnerabilities for any of our applications, because we never call the functions to read notebooks as XML. It's an abandoned avenue of development.

I'll prepare a pull request to remove the code.

**Comment by takluyver** [comment]
In fact, it was deprecated even before the notebook interface landed in master of IPython: https://github.com/ipython/ipython/commit/cc19c968a02b18e42882a57b5db7355ecb8362e3

**Comment by takluyver** [comment]
#133 removes the relevant code.

**Comment by An7i21** [comment]
Thanks, @takluyver,
Do you know when a new fixed release would be available? We are working to approve third-party libraries based on their approved releases version and the current one is still vulnerable. 
Thanks

**Comment by takluyver** [comment]
I don't think we're going to rush to get a new version out. The vulnerable code is only a problem if you call it, and none of our other packages do call it, as far as I could find. So if you don't call it from internal code, you should be fine.
