### ISSUE TITLE
Changes to notebook file formats 4.0 and 4.1.

### ISSUE THREAD

**Issue by jasongrout** [jupyter/nbformat#170]
This is a somewhat technical question, but since it deals with one of the foundational layers of Jupyter (the notebook file format), I thought I would summarize and flag the discussion before we release the changes in case someone here wanted to weigh in.

Background summary: Over the years we have documented notebook formats version 4.0, 4.1, 4.2, 4.3, and 4.4. We've also released a python package nbformat that was supposed to provide this documentation and various utilities for dealing with notebook file formats of different versions, including validating notebook files. We recently released nbformat package version 5.0 (note the notebook format is still 4.4, though). One of the things nbformat package version 5.0 did was update the routines validating notebook format versions to more precisely match the documentation. Being more strict about notebook validation has caused some pain in the community with notebooks that are (and have always been) technically noncompliant with their stated notebook version, but have always passed the nbformat validation routines before.
In particular, the complaints we've seen coming in are about notebook files that are using a feature introduced in notebook format version 4.2 where mimebundles can have arbitrary JSON keys (for example, ipywidgets uses this), but the notebook file claims it is notebook format 4.0 or 4.1. With nbformat package version 4.x validation routines, these notebooks passed validation, but with nbformat package version 5.0, these notebooks are flagged as invalid.
The problem is exposed to the user since the Jupyter Notebook refuses to load invalid notebooks, so basically people have notebooks that have been working just fine for years, and then suddenly Jupyter Notebook refuses to open the files claiming that they are invalid notebooks.

There are a couple of ways we can go here:

A. We can retroactively update notebook file formats 4.0 and 4.1 to include the change in 4.2 allowing arbitrary JSON in mimebundles. This is done in https://github.com/jupyter/nbformat/pull/169 and https://github.com/jupyter/nbformat/pull/167. Essentially, this acknowledges that, despite what the documentation said, our tools (nbformat validation routines) sanctioned a proliferation of technically noncompliant notebooks, and we are now retroactively updating the file format spec to align with the realities of the world. Currently, we are poised to release nbformat 5.0.5 (#168) with these changes as a pragmatic compromise with reality. This would mean that people affected by this specific issue would not see the error when they upgraded nbformat, and the issue would only affect nbformat 5.0.0-5.0.4.

B. Another way of looking at it is that file formats (defined in the documentation) should *never* be retroactively updated, otherwise we undercut the trust of the community. Instead, the real problem here is that Jupyter Notebook (despite what our nbformat validation routines said) and other clients were writing noncompliant files, and it is up to them to deal with the fallout. In particular, instead of Jupyter Notebook stopping when finding an invalid file, it could try updating the file format version to 4.4, or even just to the next file format version, and validating again, essentially attempting to automatically upgrade file format versions. The end result here is that people would have to upgrade the Jupyter Notebook to open these noncompliant files.

Essentially, in A we are preserving the trust of the community in our tools and undercutting trust in our documented specs, and saying that pragmatically, the file format is/was at least partly defined by the implementation of our validation routines. In B we are preserving the trust of the community in the documented file format spec, but undercutting the trust in our tools.

Thoughts?

**Comment by jasongrout** [comment]
CC @jupyter/steeringcouncil

**Comment by ivanov** [comment]
Thanks for writing this up, Jason!

It's too bad we can't have arbitrary icons as reactions, but as a light-weight way of participation and getting a sense of where folks are at with this, how about gauging preference via reaction :tada: for A and :rocket: for B and :eyes: for no preference or some other alternative.

**Comment by ivanov** [comment]
My thinking is that being the reference implementation, if our tools said something was a valid format, then it's on us to retain that as a valid format and create a minimal amount of noise for those affected by this. We can add historical notes to the affected version of of nbformat, saying that though as originally written up in the documentation, arbitrary JSON keys were not supported, the nbformat tools still resolved notebooks with arbitrary JSON keys as valid, so the format has been updated to reflect that.

**Comment by MSeal** [comment]
I had a lot of requests for B) to happen on behalf of users since they almost always didn't even know there was a notebook version and relied on notebook classic to just load things. A few of those cases would not have automatically upgraded smoothly (jupyter lab couldn't update them and the files were far from valid) but most could have in the background relatively easily. I think users "just want it to work" and only development teams really care about version spec numbers.

However A) is a slightly safer change in my opinion and the fact many of our tools behaved this way and validated as such in the past indicates our spec wasn't complete or never really enforced. I've found the users most impacted are the least capable to remedy the problem themselves, including even with re-saving files back to disk, so making those files in-place validate again seems easier to communicate and promote.

I think it maybe better to provide the function that updates older format files and have an optional flag for load calls to use said function when indicated rather than as a default behavior. Then each tool could choose if it was safe to auto-promote formats and pick the tradeoff between A) and B)? 

But I'm ok going either route A) or B) for now if there's lean one way or another.

**Comment by willingc** [comment]
Reframe of Jason's original message (without options)

## Background summary

Documentation of **notebook formats** version 4.0, 4.1, 4.2, 4.3, and 4.4.

Released a python package `nbformat` that was supposed to provide:
 - this documentation 
 - various utilities for dealing with notebook file formats of different versions
- validating notebook files. 

### Release of nbformat 5.0 (equivalent to documentation version 4.4)

We recently released `nbformat` package version 5.0 (note the **notebook format** is still 4.4, though). 

`nbformat` package version 5.0 updated the routines validating notebook format versions to more precisely match the documentation (**Notebook Format 4.4**).

### Problem: Notebook validation and compliance confusion
Non-compliant notebooks now fail validation in `nbformat` 5.0.
Being more strict about notebook validation has caused some pain in the community with notebooks that are (and have always been) technically noncompliant with their stated notebook version, but have always passed the `nbformat` validation routines before.

### Specific Problem: mimebundles with arbitrary JSON Keys
In particular, the complaints we've seen coming in are about notebook files that are using a feature introduced in **notebook format** version 4.2 where mimebundles can have arbitrary JSON keys (for example, ipywidgets uses this), but the notebook file claims it is notebook format 4.0 or 4.1. 

With `nbformat` package version 4.x validation routines, these notebooks passed validation, but with `nbformat` package version 5.0, these notebooks are flagged as invalid.

### End User Impact
The problem is exposed to the user since the Jupyter Notebook refuses to load invalid notebooks. So basically people have notebooks that have been working just fine for years, and then suddenly Jupyter Notebook refuses to open the  notebook files claiming that they are invalid notebooks.

**Comment by willingc** [comment]
## Option A: Release nbformat 5.0.5 with retroactive updates to file formats 4.0 and 4.1
We can retroactively update notebook file formats 4.0 and 4.1 to include the change in 4.2 allowing arbitrary JSON in mimebundles. This is done in #169 and #167. Essentially, this acknowledges that, despite what the documentation said, our tools (`nbformat` validation routines) sanctioned a proliferation of technically noncompliant notebooks, and we are now retroactively updating the file format spec to align with the realities of the world. Currently, we are poised to release `nbformat` 5.0.5 (#168) with these changes as a pragmatic compromise with reality. This would mean that people affected by this specific issue would not see the error when they upgraded `nbformat`, and the issue would only affect `nbformat` 5.0.0-5.0.4.

## Option B: Do not retroactively update file formats
Another way of looking at it is that file formats (defined in the documentation) should never be retroactively updated, otherwise we undercut the trust of the community. Instead, the real problem here is that Jupyter Notebook (despite what our `nbformat` validation routines said) and other clients were writing noncompliant files, and it is up to them to deal with the fallout.

In particular, instead of Jupyter Notebook stopping when finding an invalid file, it could try updating the file format version to 4.4, or even just to the next file format version, and validating again, essentially attempting to automatically upgrade file format versions. The end result here is that people would have to upgrade the Jupyter Notebook to open these noncompliant files.

## Comparison
Essentially, in A we are preserving the trust of the community in our tools and undercutting trust in our documented specs, and saying that pragmatically, the file format is/was at least partly defined by the implementation of our validation routines. In B we are preserving the trust of the community in the documented file format spec, but undercutting the trust in our tools.

**Comment by willingc** [comment]
I would lean toward Option A for a few reasons. 

Option A better reflects reality that:
- the validation tool determined the defacto specification
- high growth of project and lack of a formal JEP process caused the notebook format documentation to fall out of sync with `nbformat`

Option B to me feels like rewriting history.

Whichever option is selected, the community should be reassured that foundational changes will be done with a JEP process.

**Comment by willingc** [comment]
Ping @captainsafia

**Comment by SylvainCorlay** [comment]
I am strongly in favor of option A as the issue impacts most Jupyter widget users who had version-controled notebooks when they update nbformat.

**Comment by jasongrout** [comment]
Also ping @williamstein

**Comment by williamstein** [comment]
I personally vote for option A, and would even be tempted to try to maintain a forked version of Jupyter with option A if option B were chosen (just to reduce the support load on me).

**Comment by jasongrout** [comment]
> My thinking is that being the reference implementation, if our tools said something was a valid format, then it's on us to retain that as a valid format and create a minimal amount of noise for those affected by this.

As background, if I remember correctly, essentially what the old validation functions were doing were validating against the *latest* spec, not the spec the file claimed to satisfy. So for a long time, IIRC it was essentially validating files that said they were format 4.0 against the 4.4. spec.

Looking at the differences between format spec 4.0 and format spec 4.4 (see below), the only other change that might cause a problem like this is the addition of the `attachments` key to the markdown and raw cells introduced in format spec 4.1. In other words, there could be clients that generate files labeled as format spec 4.0, with an attachment to a markdown or raw cell, and it would have passed validation before, but won't now.


As far as I can tell, because all the other additions are in optional metadata keys, other than the mimebundle containing json and this attachment key, a valid 4.4 file should pass the 4.0 schema.

Should we backport this attachments key too, for the same reason?

<details><summary>Diff of https://github.com/jupyter/nbformat/blob/221bbc5c97e447210e53892afc4d1a33ac81fd8d/nbformat/v4/nbformat.v4.0.schema.json and https://github.com/jupyter/nbformat/blob/221bbc5c97e447210e53892afc4d1a33ac81fd8d/nbformat/v4/nbformat.v4.4.schema.json (i.e., after #171)</summary>

```diff
--- ./nbformat.v4.0.schema.json	2020-03-26 15:34:17.000000000 -0700
+++ ./nbformat.v4.4.schema.json	2020-03-26 15:37:10.000000000 -0700
@@ -1,6 +1,6 @@
 {
     "$schema": "http://json-schema.org/draft-04/schema#",
-    "description": "IPython Notebook v4.0 JSON schema.",
+    "description": "Jupyter Notebook v4.4 JSON schema.",
     "type": "object",
     "additionalProperties": false,
     "required": ["metadata", "nbformat_minor", "nbformat", "cells"],
@@ -59,13 +59,30 @@
                     "description": "Original notebook format (major number) before converting the notebook between versions. This should never be written to a file.",
                     "type": "integer",
                     "minimum": 1
+                },
+                "title": {
+                    "description": "The title of the notebook document",
+                    "type": "string"
+                },
+                "authors": {
+                    "description": "The author(s) of the notebook document",
+                    "type": "array",
+                    "item": {
+                      "type": "object",
+                      "properties": {
+                        "name": {
+                          "type": "string"
+                        }
+                      },
+                      "additionalProperties": true
+                    }
                 }
             }
         },
         "nbformat_minor": {
             "description": "Notebook format (minor number). Incremented for backward compatible changes to the notebook format.",
             "type": "integer",
-            "minimum": 0
+            "minimum": 4
         },
         "nbformat": {
             "description": "Notebook format (major number). Incremented between backwards incompatible changes to the notebook format.",
@@ -109,10 +126,20 @@
                             "description": "Raw cell metadata format for nbconvert.",
                             "type": "string"
                         },
+                        "jupyter": {
+                          "description": "Official Jupyter Metadata for Raw Cells",
+                          "type": "object",
+                          "additionalProperties": true,
+                            "source_hidden": {
+                                "description": "Whether the source is hidden.",
+                                "type": "boolean"
+                            }
+                        },
                         "name": {"$ref": "#/definitions/misc/metadata_name"},
                         "tags": {"$ref": "#/definitions/misc/metadata_tags"}
                     }
                 },
+                "attachments": {"$ref": "#/definitions/misc/attachments"},
                 "source": {"$ref": "#/definitions/misc/source"}
             }
         },
@@ -132,10 +159,20 @@
                     "type": "object",
                     "properties": {
                         "name": {"$ref": "#/definitions/misc/metadata_name"},
-                        "tags": {"$ref": "#/definitions/misc/metadata_tags"}
+                        "tags": {"$ref": "#/definitions/misc/metadata_tags"},
+                        "jupyter": {
+                          "description": "Official Jupyter Metadata for Markdown Cells",
+                          "type": "object",
+                          "additionalProperties": true,
+                            "source_hidden": {
+                                "description": "Whether the source is hidden.",
+                                "type": "boolean"
+                            }
+                        }
                     },
                     "additionalProperties": true
                 },
+                "attachments": {"$ref": "#/definitions/misc/attachments"},
                 "source": {"$ref": "#/definitions/misc/source"}
             }
         },
@@ -155,8 +192,49 @@
                     "type": "object",
                     "additionalProperties": true,
                     "properties": {
+                        "jupyter": {
+                          "description": "Official Jupyter Metadata for Code Cells",
+                          "type": "object",
+                          "additionalProperties": true,
+                            "source_hidden": {
+                                "description": "Whether the source is hidden.",
+                                "type": "boolean"
+                            },
+                            "outputs_hidden": {
+                                "description": "Whether the outputs are hidden.",
+                                "type": "boolean"
+                            }
+                        },
+                        "execution": {
+                            "description": "Execution time for the code in the cell. This tracks time at which messages are received from iopub or shell channels",
+                            "type": "object",
+                            "properties": {
+                                "iopub.execute_input": {
+                                    "description": "header.date (in ISO 8601 format) of iopub channel's execute_input message. It indicates the time at which the kernel broadcasts an execute_input message to connected frontends",
+                                    "type": "string"
+                                },
+                                "iopub.status.busy": {
+                                    "description": "header.date (in ISO 8601 format) of iopub channel's kernel status message when the status is 'busy'",
+                                    "type": "string"
+                                },
+                                "shell.execute_reply": {
+                                    "description": "header.date (in ISO 8601 format) of the shell channel's execute_reply message. It indicates the time at which the execute_reply message was created",
+                                    "type": "string"
+                                },
+                                "iopub.status.idle": {
+                                    "description": "header.date (in ISO 8601 format) of iopub channel's kernel status message when the status is 'idle'. It indicates the time at which kernel finished processing the associated request",
+                                    "type": "string"
+                                }
+                            },
+                            "additionalProperties": true,
+                            "patternProperties": {
+                                "^.*$": {
+                                    "type": "string"
+                                }
+                            }
+                        },
                         "collapsed": {
-                            "description": "Whether the cell is collapsed/expanded.",
+                            "description": "Whether the cell's output is collapsed/expanded.",
                             "type": "boolean"
                         },
                         "scrolled": {
@@ -180,7 +258,7 @@
                 }
             }
         },
-        
+
         "unrecognized_cell": {
             "description": "Unrecognized cell from a future minor-revision to the notebook format.",
             "type": "object",
@@ -204,7 +282,7 @@
                 }
             }
         },
-        
+
         "output": {
             "type": "object",
             "oneOf": [
@@ -314,7 +392,7 @@
 
         "misc": {
             "metadata_name": {
-                "description": "The cell's name. If present, must be a non-empty string.",
+                "description": "The cell's name. If present, must be a non-empty string. Cell names are expected to be unique across all the cells in a given notebook. This criterion cannot be checked by the json schema and must be established by an additional check.",
                 "type": "string",
                 "pattern": "^.+$"
             },
@@ -327,6 +405,16 @@
                     "pattern": "^[^,]+$"
                 }
             },
+            "attachments": {
+                "description": "Media attachments (e.g. inline images), stored as mimebundle keyed by filename.",
+                "type": "object",
+                "patternProperties": {
+                    ".*": {
+                        "description": "The attachment's data stored as a mimebundle.",
+                        "$ref": "#/definitions/misc/mimebundle"
+                    }
+                }
+            },
             "source": {
                 "description": "Contents of the cell, represented as an array of lines.",
                 "$ref": "#/definitions/misc/multiline_string"
```

</details>

**Comment by jasongrout** [comment]
> Should we backport this attachments key from format spec 4.1 to format spec 4.0 for the same reason?

This is now https://github.com/jupyter/nbformat/pull/172, in case we decide to do this too.

This change makes notebook format 4.0 and 4.1 identical.

**Comment by MSeal** [comment]
I think this follows the arguments made above for plan A). Any objections to merging and releasing the change @jasongrout made?

**Comment by captainsafia** [comment]
> I think this follows the arguments made above for plan A). Any objections to merging and releasing the change @jasongrout made?

Nope! Seems sensible.

**Comment by jasongrout** [comment]
I've documented changes to the format in #174.

**Comment by jasongrout** [comment]
Since there are now a number of positive comments for option A over the last 5 days, including explicit community and steering council votes for option A, and no one here is supporting the other options or proposing a different option, we plan to move forward with option A, as well as #172 (backporting the attachments key as well) and #174 (documenting these changes).

**Comment by jasongrout** [comment]
Closing as discussion resolved. Thanks everyone!
