### ISSUE TITLE
delete and recreate signature db if corrupted.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbformat#26]
likely fix for  https://github.com/ipython/ipython/issues/9003

**Comment by Carreau** [comment]
Min, please don't fix it too fast, I'm trying to find a few easy issues for a new contributor.

**Comment by jamesfe** [comment]
@minrk Hi - I found this issue via the ipython repo and would love to help with it.  I'm still new to this - but would likely take the advice @Carreau provided and check the exception...the only problem is I'm unsure of the workflow to test `nbformat` in isolation.  How do you run tests?  Do you have any advice for me in terms of writing the tests that will accompany this pull request?

**Comment by takluyver** [comment]
Hi @jamesfe ! Tests are run with the command `nosetests`.

Testing the fix for this will be a bit fiddly. We'll need to deliberately create a file that will cause sqlite to throw `DatabaseError`, and point a NotebookNotary to that file. A smoke test will probably be enough: making sure that the `check_signature` method runs without throwing an error.

**Comment by jamesfe** [comment]
Thanks!  Will get to work on that.  I appreciate the quick response!

**Comment by Carreau** [comment]
> How do you run tests?

The other possibility is to just make a PR and let Travis test. It is a valid approach.
We can of course help with writing the test if you are stuck.

**Comment by jamesfe** [comment]
I'm chugging along pretty well, I've gotten the tests running and will be writing at least one new test shortly to ensure what I'm doing isn't completely insane.  Travis will be telling though :)

**Comment by minrk** [comment]
closed by #32
